version: '2'
services:
  ensref.db:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9032:5432"
    volumes:
#      - "./data/db:/var/lib/postgresql/data"
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_ensref
      - POSTGRES_USER=usr_ensref
      - POSTGRES_PASSWORD=ensref
      
