language: java
jdk: oraclejdk8
dist: trusty

services:
  - docker

before_script:
  - docker-compose -f docker/dev/docker-compose.yml stop
  - docker-compose -f docker/dev/docker-compose.yml rm -v
  - docker-compose -f docker/dev/docker-compose.yml up -d

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
